repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.26
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest -vv --cov=src --cov-report term-missing:skip-covered
        language: python
        pass_filenames: false
        always_run: true
      - id: repo-map
        name: repo_map
        entry: uv run -m repo_mapper
        language: system
        pass_filenames: false
        args:
          - --repo-root
          - .
          - --readme-path
          - ./README.md
          - --gitignore-path
          - ./.gitignore
          - --allowed-exts
          - py,md,yaml,toml,lock
          - --ignore-dirs
          - .venv,target,.git,mock_data,.pytest_cache
          # - --ignore-hidden
      - id: update-readme
        name: update_readme
        entry: uv run -m dev_tools.update_readme
        language: python
        pass_filenames: false
        always_run: true